-- MySQL Script generated by MySQL Workbench
-- Mon Jul 13 13:28:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `city_Id` INT NOT NULL AUTO_INCREMENT,
  `city_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_Id`),
  UNIQUE INDEX `city_Name_UNIQUE` (`city_Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_Id` INT NOT NULL AUTO_INCREMENT,
  `user_FirstName` VARCHAR(45) NOT NULL,
  `user_LastName` VARCHAR(45) NOT NULL,
  `user_PhoneNumber` VARCHAR(45) NOT NULL,
  `user_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_Id`),
  UNIQUE INDEX `user_PhoneNumber_UNIQUE` (`user_PhoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `user_Email_UNIQUE` (`user_Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trips` (
  `trip_Id` INT NOT NULL AUTO_INCREMENT,
  `trip_DepartureDateTime` DATETIME NOT NULL,
  `trip_ArrivalDateTime` DATETIME NOT NULL,
  `trip_Space` INT NOT NULL,
  `trip_DepartureCityId` INT NOT NULL,
  `trip_CreatorUserId` INT NOT NULL,
  `trip_ArrivalCityId` INT NOT NULL,
  PRIMARY KEY (`trip_Id`),
  INDEX `fk_trips_cities_idx` (`trip_DepartureCityId` ASC) VISIBLE,
  INDEX `fk_trips_users1_idx` (`trip_CreatorUserId` ASC) VISIBLE,
  INDEX `fk_trips_cities1_idx` (`trip_ArrivalCityId` ASC) VISIBLE,
  CONSTRAINT `fk_trips_cities`
    FOREIGN KEY (`trip_DepartureCityId`)
    REFERENCES `mydb`.`cities` (`city_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trips_users1`
    FOREIGN KEY (`trip_CreatorUserId`)
    REFERENCES `mydb`.`users` (`user_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trips_cities1`
    FOREIGN KEY (`trip_ArrivalCityId`)
    REFERENCES `mydb`.`cities` (`city_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
