-- MySQL Script generated by MySQL Workbench
-- Mon Jul 13 14:43:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TouchePasAuKlaxon_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TouchePasAuKlaxon_DB` ;

-- -----------------------------------------------------
-- Schema TouchePasAuKlaxon_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TouchePasAuKlaxon_DB` DEFAULT CHARACTER SET utf8 ;
USE `TouchePasAuKlaxon_DB` ;

-- -----------------------------------------------------
-- Table `TouchePasAuKlaxon_DB`.`agencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TouchePasAuKlaxon_DB`.`agencies` (
  `agency_Id` INT NOT NULL AUTO_INCREMENT,
  `agency_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`agency_Id`),
  UNIQUE INDEX `agency_Name_UNIQUE` (`agency_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TouchePasAuKlaxon_DB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TouchePasAuKlaxon_DB`.`users` (
  `user_Id` INT NOT NULL AUTO_INCREMENT,
  `user_FirstName` VARCHAR(45) NOT NULL,
  `user_LastName` VARCHAR(45) NOT NULL,
  `user_PhoneNumber` VARCHAR(45) NOT NULL,
  `user_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_Id`),
  UNIQUE INDEX `user_PhoneNumber_UNIQUE` (`user_PhoneNumber`),
  UNIQUE INDEX `user_Email_UNIQUE` (`user_Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TouchePasAuKlaxon_DB`.`trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TouchePasAuKlaxon_DB`.`trips` (
  `trip_Id` INT NOT NULL AUTO_INCREMENT,
  `trip_DepartureDateTime` DATETIME NOT NULL,
  `trip_ArrivalDateTime` DATETIME NOT NULL,
  `trip_Space` INT NOT NULL,
  `trip_CreatorUserId` INT NOT NULL,
  `trip_DepartureAgencyId` INT NOT NULL,
  `trip_ArrivalAgencyId` INT NOT NULL,
  PRIMARY KEY (`trip_Id`),
  INDEX `fk_trip_user_idx` (`trip_CreatorUserId`),
  INDEX `fk_trip_departure_agency_idx` (`trip_DepartureAgencyId`),
  INDEX `fk_trip_arrival_agency_idx` (`trip_ArrivalAgencyId`),
  CONSTRAINT `fk_trip_user`
    FOREIGN KEY (`trip_CreatorUserId`)
    REFERENCES `TouchePasAuKlaxon_DB`.`users` (`user_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trip_departure_agency`
    FOREIGN KEY (`trip_DepartureAgencyId`)
    REFERENCES `TouchePasAuKlaxon_DB`.`agencies` (`agency_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trip_arrival_agency`
    FOREIGN KEY (`trip_ArrivalAgencyId`)
    REFERENCES `TouchePasAuKlaxon_DB`.`agencies` (`agency_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_different_agencies`
	  CHECK(`trip_DepartureAgencyId` <> `trip_ArrivalAgencyId`),
  CONSTRAINT `chk_trip_space`
    CHECK(`trip_Space`> 0),
  CONSTRAINT `chk_trip_dates`
    CHECK(`trip_ArrivalDateTime`> `trip_DepartureDateTime`)
  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;